import BaseModal from "@/globals/components/layouts/BaseModal";
import Button from "@/globals/components/layouts/Button";

type ManualModalProps = {
  isOpen: boolean;
  onClose: () => void;
};

const ManualModal = ({ isOpen, onClose }: ManualModalProps) => (
  <BaseModal isOpen={isOpen} onClose={onClose} className="max-w-xl">
    <div className="mb-8">
      <h2 className="text-3xl font-black uppercase tracking-wide text-white">
        Operation Manual
      </h2>
      <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-emerald-400">
        Protocol & Interface Guide
      </p>
    </div>

    <div className="space-y-8">
      {/* Section 1: The Objective */}
      <section className="space-y-3">
        <h3 className="text-[11px] font-black uppercase tracking-widest text-slate-500 flex items-center gap-2">
          <span className="h-px w-4 bg-slate-800" /> 01. The Objective
        </h3>
        <p className="text-sm text-slate-300 leading-relaxed">
          Watch the sequence of lights and sounds generated by the system.
          Repeat the sequence exactly as shown. Each successful round adds one
          new step to the pattern.
        </p>
      </section>

      {/* Section 2: Hardware Controls */}
      <section className="space-y-3">
        <h3 className="text-[11px] font-black uppercase tracking-widest text-slate-500 flex items-center gap-2">
          <span className="h-px w-4 bg-slate-800" /> 02. Hardware Interface
        </h3>
        <div className="grid grid-cols-2 gap-4">
          <div className="rounded-xl bg-white/5 border border-white/10 p-4">
            <p className="text-[10px] font-bold text-white uppercase mb-1">
              Physical Mode
            </p>
            <p className="text-[11px] text-slate-400">
              Connect your Arduino via the{" "}
              <span className="text-blue-400 italic">Controller Settings</span>.
              Use the tactile buttons for zero-latency input.
            </p>
          </div>
          <div className="rounded-xl bg-white/5 border border-white/10 p-4">
            <p className="text-[10px] font-bold text-white uppercase mb-1">
              Standard Mode
            </p>
            <p className="text-[11px] text-slate-400">
              If no hardware is detected, use your{" "}
              <span className="text-emerald-400 italic">Mouse or Touch</span> to
              interact with the virtual buttons.
            </p>
          </div>
        </div>
      </section>

      {/* Section 3: Technical Specs */}
      {/* <section className="space-y-3">
        <h3 className="text-[11px] font-black uppercase tracking-widest text-slate-500 flex items-center gap-2">
          <span className="h-px w-4 bg-slate-800" /> 03. System Constraints
        </h3>
        <div className="rounded-xl bg-black/40 border border-white/5 p-4 font-mono text-[10px] text-slate-400">
          <ul className="space-y-1">
            <li className="flex justify-between">
              <span>Sequence Delay:</span>
              <span className="text-white">400ms</span>
            </li>
            <li className="flex justify-between">
              <span>Input Window:</span>
              <span className="text-white">Unlimited</span>
            </li>
            <li className="flex justify-between">
              <span>Failure Condition:</span>
              <span className="text-red-400 uppercase">Mistyped Input</span>
            </li>
          </ul>
        </div>
      </section> */}

      <Button
        text="Acknowledge & Close"
        onClick={onClose}
        className="w-full h-14"
      />
    </div>
  </BaseModal>
);

export default ManualModal;
